// <auto-generated />
namespace nmct.ssa.labo2.webshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addname));
        
        string IMigrationMetadata.Id
        {
            get { return "201502171604393_Add name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
